### ISSUE TITLE
is it possible to derive a pedestrian's visibility score?

### ISSUE THREAD

**Issue by SamihaSara** [thomascong121/SocialDistance#1]

**Comment by thomascong121** [comment]
Hi, If you refer to the probability of the object being a pedestrian then you can use the models in[ this link](https://github.com/dmlc/gluon-cv) to reproduce.

**Comment by SamihaSara** [comment]
Sorry, I was not referring to the probability of the object being a pedestrian. I have a pedestrian dataset, with bounding box and corresponding visibility score(how much of the object is visible because of occlusion).

**Comment by thomascong121** [comment]
The current code does not provide such an output. One possible solution is to use the intersection of the bounding boxes as the occlusion score and then minus that from the total area of the bounding box as a rough estimation of the visibility score.

**Comment by SamihaSara** [comment]
@thomascong121 Thanks for your suggestion. Could you please advise
1) To calculate this intersection, how to set a radius around a bounding box that could be equal to its area, to calculate an intersection with only its adjacent bounding boxes?

2) Where can I find codes for this operation
" a distance computation technique with a locally adaptive threshold to approximate the actual spatial distance between pedestrians in the real world."?

3) If a pedestrian is occluded by more than one pedestrian, then how to estimate the occlusion score as the intersection of the bounding boxes?

4) https://github.com/thomascong121/SocialDistance/blob/master/SDD/debug/camera_colibration.ipynb
Here, how did you find keypoints_birds_eye_view and keypoints values? I am trying to figure out, how to find distances in a custom dataset.

**Comment by thomascong121** [comment]
Sorry for the late reply, I was busying working on another paper and forget to reply. In our case, I believe we calculate the threshold based on a person's height and this could be roughly approximated by the height of the bounding box (or if you can come up with some better approximations). As for the keypoint values, you need to measure from the bird-eye frame and the frame generated by `cv2.warpPerspective`.
